service:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    container_name: Frontend_Container
    port: ["3000:3000"]
    command: npm run dev -- --host 0.0.0.0
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    enviroment:
      - CHOKIDAR_USEPOLLING=true
    networks: ["app-network"]

  backend:
    build: ./backend
    depends_on:
      -mysql
    container_name: Backend_Container
    ports: ["3001:3001"]
    command: npx -y nodemon -L index.js
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_DATABASE: protest10
      JWT_SECRET: "Tee&Kate"
      CHOKIDAR_USEPULLING: true
    networks: ["app-network"]

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    container_name: PMA_Container
    ports: ["8080:80"]
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 1234
    network: ["app-network"]

  mysql:
  image: mysql
  container_name: MYSQL_Container
  ports: ["3305:3306"]
  restart: always
  volumes:
    - ./database:/docker-entrypoint-initdb.d
    - mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: protest10
  networks: ["app-network"]

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: